### ISSUE TITLE
Controller reference still remains after popping it, due to which I get null pointer exception when activity back pressed

### ISSUE THREAD

**Issue by ashank96** [sockeqwe/mosby-conductor#40]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isChangingConfigurations()' on a null object reference
        at com.hannesdorfmann.mosby3.conductor.viewstate.delegate.MvpViewStateConductorLifecycleListener.preDestroyView(MvpViewStateConductorLifecycleListener.java:45)
        at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:972)
        at com.bluelinelabs.conductor.Controller.detach(Controller.java:960)
        at com.bluelinelabs.conductor.Controller$7.onDetached(Controller.java:1039)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportDetached(ViewAttachHandler.java:103)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler.onViewDetachedFromWindow(ViewAttachHandler.java:58)
        at android.view.View.dispatchDetachedFromWindow(View.java:19088)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3924)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3916)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4187)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:7581)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:7555)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:500)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:438)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:132)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4688)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by sockeqwe** [comment]
Which version of conductor do you use?

Ashank Bharati <notifications@github.com> schrieb am Mo. 9. Sep. 2019 um
13:12:
